Login/urls.py
from django.urls import path
from Login import views


app_name = 'Login'

urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('verify_email/<str:uidb64>/<str:token>/', views.verify_email, name='verify_email'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password/<str:uidb64>/<str:token>/', views.reset_password, name='reset_password'),

]

Main/urls.py
from django.contrib import admin
from django.urls import path, include

#show media files
from django.conf import settings
from django.contrib. staticfiles.urls import static

from Main import views
app_name = 'Main'
urlpatterns = [
    path('', views.home, name="home"),
    path('admin/', admin.site.urls),
    path('account/', include('Login.urls')),
    path('models/', include('Models.urls')),
    path('ckeditor/', include("ckeditor_uploader.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Models/urls.py
from django.urls import path
from . import views

app_name = 'Models'

urlpatterns = [
    path('create-model/', views.create_model, name='create_model'),
    path('models',views.models_list, name='models_list'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'custom_css/style.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'ckeditor/ckeditor.js' %}"></script>
    <title>{% block title %} {% endblock %}</title>
    {% block head %} {% endblock %}
  </head>
  <body>
    <body>
      <section style="">
        {% include 'navmenu.html' %}
        <div class="container" style="padding-top:5px">
          <div class="messages container mt-2">
            {% if messages %}
              {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{message.tags}} {% endif %}" role="alert">
                  {{message}}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
              {% endfor %}
    
            {% endif %}
    
          </div>
          {% block body %} {% endblock %}
        </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
  </body>
</html>

templates/home.html
{% extends 'base.html' %} 
 {% block title %} Home{% endblock %}
 {% block body %}  
 <div class="bg-light">  
<h2>9neurons</h2>

<br />
<p>Doesn't have an account?</p>
<a href="{% url 'Login:registration' %}">SignUp</a> 
 </div>
{% endblock %}

templates/navmenu.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">9neurons</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'Login:profile' %}">Profile</a>
        </li>
        {% else %}
        <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'Login:login' %}">Login</a>
      </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'Models:models_list' %}">Models</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>