Main/urls.py
from django.contrib import admin
from django.urls import path, include

#show media files
from django.conf import settings
from django.contrib. staticfiles.urls import static

from Main import views
app_name = 'Main'
urlpatterns = [
    path('', views.home, name="home"),
    path('admin/', admin.site.urls),
    path('account/', include('Login.urls')),
    path('models/', include('Models.urls')),
    path('ckeditor/', include("ckeditor_uploader.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Models/urls.py
from django.urls import path
from . import views

app_name = 'Models'

urlpatterns = [
    path('create-model/', views.create_model, name='create_model'),
    path('models',views.models_list, name='models_list'),
]

Login/models.py
from django.db import models

#Create automatic one to one object profile
from django.db.models.signals import post_save
from django.dispatch import receiver
# Custom user & admin panel
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy




class MyUserManager(BaseUserManager):
    #custom login with email
    def _create_user(self, email, password, **extra_fields):

        #save user email and password
        if not email:
            raise ValueError("Email must be set")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('SuperUser must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('SuperUser must have is_superuser=True')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('approve', 'Approved'),
        ('disapprove', 'Disapproved'),
    )
    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Transgender', 'Transgender'),
    )
    USERTYPE_CHOICES = (
        ('Visitor', 'Visitor'),
        ('Member', 'Member'),
        ('Premium Member', 'Premium Member'),
    )
    email = models.EmailField(unique=True, null=False)
    full_name = models.CharField(max_length=150, null=True, blank=True)
    country = models.CharField(max_length=200, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    github = models.CharField(max_length=100, null=True, blank=True)
    university = models.CharField(max_length=150, null=True, blank=True)
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    user_type = models.CharField(max_length=50, choices=USERTYPE_CHOICES, default="Visitor")
    verification_token = models.CharField(max_length=256, blank=True, null=True)
    email_verify = models.BooleanField(default=False)

    


    is_staff = models.BooleanField(
        gettext_lazy('staff Status'),
        default = False,
        help_text = gettext_lazy('Designates whether the user can login this site')
    )

    is_active = models.BooleanField(
        gettext_lazy('active'),
        default = True,
        help_text = gettext_lazy('Designates whether this user should be treated as active. Unselect this instead of deleting accounts')

    )

    USERNAME_FIELD = 'email'
    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

Models/models.py
from django.db import models
from Login.models import User
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField

class Category(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    slug = models.SlugField(max_length=250, unique=True, blank=True)


    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    
class Sub_Category(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    slug = models.SlugField(max_length=250, unique=True, blank=True)


    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Sub_Category, self).save(*args, **kwargs)

class Model(models.Model):
    STATUS = (
        ("Pending", "Pending"),
        ("Reject", "Reject"),
        ("Aprove", "Aprove"),
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE, null=True, blank=True)
    content = RichTextUploadingField(blank=False, null=False)
    publish_date = models.DateField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)
    status = models.CharField(choices=STATUS, default="Pending", max_length=20)
    slug = models.SlugField(max_length=250, unique=True, blank=True)

    class Meta:
        ordering = ['publish_date']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Model, self).save(*args, **kwargs)
    

class Files(models.Model):
    model_name = models.ForeignKey(Model, on_delete=models.CASCADE)
    file = models.FileField(upload_to= 'files', null=True, blank=True)

Models/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import *
from Models.Forms import ModelForm, ModelFilesForm
from django.http import HttpResponseRedirect
from django.urls import reverse

# @login_required
# def create_model(request):
#     if request.user.user_type in ['Member', 'Premium Member']:
#         if request.method == 'POST':
#             form = ModelFilesForm(request.POST)
#             if form.is_valid():
#                 model = form.save(commit=False)
#                 model.author = request.user
#                 model.save()
#                 return HttpResponseRedirect(reverse('Login:profile'))
#         else:
#             form = ModelForm()
#         return render(request, 'model/create_model.html', {'form': form})
#     else:
#         return render(request, 'loging/profile.html.html')


@login_required
def create_model(request):
    if request.user.user_type in ['Member', 'Premium Member']:
        if request.method == 'POST':
            form = ModelFilesForm(request.POST, request.FILES)
            if form.is_valid():
                model = form.save(commit=False)
                model.author = request.user
                model.save()
                
                # Save the associated files
                uploaded_files = request.FILES.getlist('file')  # Get list of uploaded files
                
                for uploaded_file in uploaded_files:
                    Files.objects.create(model_name=model, file=uploaded_file)
                
                return HttpResponseRedirect(reverse('Login:profile'))
        else:
            form = ModelFilesForm()
        return render(request, 'model/create_model.html', {'form': form})
    else:
        return render(request, 'permission_denied.html')



def models_list(request):
    models = Model.objects.all()
    category = Category.objects.all()
    context = {
        'models': models,
        'category': category,
    }

    return render(request, 'model/models.html', context)

templates/model/Create_model.html
{% extends 'base.html' %} {% load static %}
{% block title %} Create Models{% endblock %}
{% block head %} 
<script src="{% static 'ckeditor/ckeditor.js' %}"></script>
{% endblock %}
{% block body %}

<h2 class="mb-1 text-center border bg-light">Create a New Model</h2>
<div class="container mt-2 pt-3 pb-10 border bg-light">
  <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">Title</label>
      <input class="form-control" {{ form.title }}
    </div>
     {% comment %} <div class="mb-3 d-grid">
      <label for="{{ form.title.id_for_label }}" class="form-label">{{ form.title.label }}</label>
      {{ form.title }}
      <div class="invalid-feedback">Please provide a title.</div>
    </div> {% endcomment %}
    <div class="mb-3">
      <label for="{{ form.sub_category.id_for_label }}" class="form-label">{{ form.sub_category.label }}</label>
      {{ form.sub_category }}
      <div class="invalid-feedback form-control">Please select a category.</div>
    </div>
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">Content</label>
       {{form.media}}{{ form.content }}
    </div>
   
    
    <div id="file-fields" class="mb-3">
      <label for="file" class="form-label">Upload Files:</label>
      <input type="file" name="file" class="form-control-file file-input" multiple>
    </div>
    <div>
    <button type="button" id="add-file-field" class="btn btn-outline-info mb-3">Add File Field</button>
    </div>
    <div class="d-grid pb-4">
    <button type="submit" class="btn btn-outline-success">Submit</button>
    </div>
  </form>
</div>

<script>
  CKEDITOR.replace('editor');
</script> 

<script>
  const fileFieldsContainer = document.getElementById('file-fields');
  const addFileFieldButton = document.getElementById('add-file-field');

  addFileFieldButton.addEventListener('click', () => {
    const newFileInput = document.createElement('input');
    newFileInput.type = 'file';
    newFileInput.name = 'file';
    newFileInput.className = 'form-control-file file-input';
    newFileInput.setAttribute('multiple', 'true');
    fileFieldsContainer.appendChild(newFileInput);
  });
</script> 


{% endblock %}

templates/model/models.html
{% extends 'base.html' %}
{% block title %}{{profile.full_name}}'s profiles' {% endblock %}
{% block body %} 
  
{% comment %} breadcrumb {% endcomment %}
  <div class="m-2">
    <nav aria-label="breadcrumb" class="">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Models</li>
      </ol>
    </nav>
  </div>
  {% comment %} End breadcrumb {% endcomment %}

  <div class="row m-2">
    {% comment %} left sidebar {% endcomment %}
    <div class="col-md-3 col-lg-3 col-sm-12 bg-light rounded-start border border-warning-subtle">
      {% for category in category %}
        <h5 class='border'>{{category.name}}</h5>
        {% for sub_category in category.sub_category_set.all %}
         <a class="border rounded border-primary hover" style= "text-decoration: none; margin-button: 2px;" href="">{{sub_category.name}}</a>
        {% endfor %}
      {% endfor %}
    </div>
    {% comment %} end left sidebar {% endcomment %}

    {% comment %} Models List {% endcomment %}
    <div class="col-md-9 col-lg-9 col-sm-12 bg-light rounded-end border border-warning-subtle">
      adad
    </div>
    {% comment %} end models list {% endcomment %}
  </div>


  
{% endblock %}